### PR TITLE
graph summarization based on bisimulation

### PR DESCRIPTION
**Pull request by shahankhatch**
Shahan Khatchadourian, Mariano P. Consens:
Constructing Bisimulation Summaries on a Multi-Core Graph Processing Framework. GRADES@SIGMOD/PODS 2015: 8:1-8:7

Link: http://event.cwi.nl/grades2015/08-khatchadourian.pdf

### CODE REVIEW

**Comment by akyrola** [comment]
This is very cool work!

However, I'd rather not merge this with the GraphChi main branch, as it makes it larger and adds dependencies. I would suggesting creating a separate GitHub project for this work.

**Comment by shahankhatch** [comment]
Thank you for taking a look so quickly. Your preference is understandable. I have a GitHub project [ScalableGraphSummaries](https://github.com/shahankhatch/ScalableGraphSummaries) with the Hadoop-based and GraphChi-based summarization implementations. 
I welcome any feedback you have on the code I was proposing to merge.

**Comment by shahankhatch** [comment]
I wanted to add that I will reduce the summarization code to the bare essentials without the dependencies so that hopefully it can be merged.

**Comment by shahankhatch** [comment]
@akyrola I have updated the graph summarization code. To support storing graphs without duplicate edges I have updated FastSharder. FastSharder now supports sorting by edge values, and also removing duplicates based on edge values. Can you please let me know your thoughts?

**Comment by shahankhatch** [comment]
Just pinging to see if there is a chance to get this PR accepted. Maybe it should be split into two PRs? One for the modifications to GraphChi core with the distinct edge addition, and another PR for the bisimulation code (which does not require dependencies and is a pure GraphChi implementation).

**Pull request closed without merging**
